language: node_js

node_js:
  - 12

branches:
  only:
    - master

script:
  - echo "No tests"

after_script:
  - ssh -i ./deploy_key travis@165.22.165.76 "cd /var/illustra-website && git pull && docker-compose up -d --build"

before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out ./deploy_key -d
  - chmod 600 ./deploy_key
  - echo "|1|wn3CNoX07DkgoNDNslWdIPM640g=|CdhTw4tUzIX3QOm4ti7EiJ0/+wI= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBK0fEPa+rBy+4jIRBKw1jzZdvZva7uZI59r3klxMf6pcLUbJ7SysGsD9nOYNtbEFfjkHVTcoTjbDfdzOO66TGDY=" >> $HOME/.ssh/known_hosts